/**
 * Sample gallery configuration.
 *
 * Three categories served from `public/images/<category>/`. Each entry names a
 * real file in that folder; add a file and list it here to make it appear.
 * Names are URL-encoded at resolve time, so spaces and parentheses are fine.
 *
 * A file that is missing is skipped at runtime rather than rendered as a broken
 * thumbnail, so the gallery stays presentable while a folder is half-filled.
 *
 * Descriptions state what each file ACTUALLY contains — verified by running the
 * metadata parser over it, not assumed from the folder name. A category name
 * says what the group is meant to exercise; several images here deliberately
 * carry no metadata at all, and the copy says so. PixelGuard reports what it
 * finds, and it is allowed to disagree with the folder it came from.
 */

export const SAMPLE_CATEGORIES = [
  {
    id: 'ai-generated',
    dir: '/images/ai-generated',
    title: 'AI Generated',
    blurb: 'Images produced by a generative model. Where a provenance marker survives, the metadata parser finds it — where it does not, the visual read has to stand on its own.',
    expects: 'Expected: AI Generated when a provenance marker survives; otherwise the visual read decides.',
    tone: 'text-fuchsia-700 dark:text-fuchsia-300 border-fuchsia-600/30 dark:border-fuchsia-500/30 bg-fuchsia-500/10',
    samples: [
      {
        file: 'Gemini_Generated_Image_jm7mr5jm7mr5jm7m.jpg',
        title: 'SynthID provenance',
        // Verified: parser matches "synthid" in the raw container.
        detail: 'Generated by Google Imagen and still carrying a SynthID marker in the file.',
      },
      {
        file: 'image.png',
        title: 'Generated, metadata stripped',
        detail: 'No metadata survives, so nothing corroborates the visual read — the common case for anything re-saved or downloaded.',
      },
      {
        file: 'Pasted image.png',
        title: 'Pasted from clipboard',
        detail: 'Clipboard paste discards the original container, and with it any provenance marker.',
      },
    ],
  },
  {
    id: 'camera-exif',
    dir: '/images/camera-exif',
    title: 'Camera EXIF',
    blurb: 'How PixelGuard treats capture metadata. EXIF is trivially forged and routinely stripped, so it is weighed against the visual read rather than trusted.',
    expects: 'Expected: capture EXIF reported where present; any disagreement with the visual read is surfaced, not resolved.',
    tone: 'text-emerald-700 dark:text-emerald-300 border-emerald-600/30 dark:border-emerald-500/30 bg-emerald-500/10',
    samples: [
      {
        file: 'sample1.jpg',
        title: 'Full capture EXIF',
        // Verified: DateTimeOriginal, ExposureTime, FNumber, FocalLength, ISO.
        detail: 'Procedurally drawn, then given body, lens, exposure and GPS EXIF — so the two evidence sources disagree on purpose.',
      },
      {
        file: 'tiger.jpg',
        title: 'Photograph, EXIF stripped',
        detail: 'A photograph whose capture metadata is gone, as it would be after almost any upload.',
      },
      {
        file: 'apple.jpg',
        title: 'Product shot, no metadata',
        detail: 'Nothing left to corroborate or contradict the visual read.',
      },
    ],
  },
  {
    id: 'composite',
    dir: '/images/composite',
    title: 'Composite',
    blurb: 'Images assembled from more than one source. ELA renders the compression history for a human to read — on its own it never proves manipulation.',
    expects: 'Expected: an ELA heatmap for visual review. ELA alone is not evidence of tampering.',
    tone: 'text-amber-700 dark:text-amber-300 border-amber-600/30 dark:border-amber-500/30 bg-amber-500/10',
    samples: [
      { file: 'compose.jpg', title: 'Composite A', detail: 'Assembled from multiple sources and re-saved, which is what erases most of the ELA trace.' },
      { file: 'compose2.jpg', title: 'Composite B', detail: 'A second composite, for comparing how differently two edits register.' },
      { file: '2-Figure2-1.png', title: 'Side-by-side figure', detail: 'Panels from different sources in one frame — distinct compression histories in a single image.' },
    ],
  },
]

/** Resolve a file in a category folder, or null when it is not there. */
export function resolveSampleUrl(dir, file) {
  return new Promise((resolve) => {
    if (typeof Image === 'undefined' || !file) return resolve(null)
    // Encode the name only: spaces and parentheses are common in dropped files.
    const url = `${dir}/${encodeURIComponent(file)}`
    const img = new Image()
    img.onload = () => resolve(url)
    img.onerror = () => resolve(null)
    img.src = url
  })
}
