/**
 * Sample gallery configuration.
 *
 * Images are DISCOVERED, not listed. Every file under
 * `src/assets/samples/<category>/` is picked up automatically by Vite's glob,
 * so dropping a file into a folder makes it appear with no edit here — and
 * removing one makes it disappear without leaving a dead entry behind.
 *
 * They live under `src/assets/` rather than `public/` precisely so this
 * enumeration is possible: nothing can list a directory in `public/` at
 * runtime, which is why a hand-maintained array drifted out of sync with the
 * folder in the first place.
 *
 * DESCRIPTIONS below is optional per-file copy. A file with no entry still
 * shows, captioned from its filename. Anything written here states what the
 * file ACTUALLY contains — verified with the metadata parser, not inferred from
 * the folder it sits in. A category name says what the group is meant to
 * exercise; PixelGuard still reports whatever it finds, and it may disagree.
 */

// Eager so URLs are available synchronously on first render.
const FILES = import.meta.glob('../assets/samples/*/*.{png,jpg,jpeg,webp,PNG,JPG,JPEG,WEBP}', {
  eager: true,
  query: '?url',
  import: 'default',
})

export const CATEGORY_META = {
  'ai-generated': {
    title: 'AI Generated',
    blurb: 'Images produced by a generative model. Where a provenance marker survives, the metadata parser finds it — where it does not, the visual read has to stand on its own.',
    expects: 'Expected: AI Generated when a provenance marker survives; otherwise the visual read decides.',
    tone: 'text-fuchsia-700 dark:text-fuchsia-300 border-fuchsia-600/30 dark:border-fuchsia-500/30 bg-fuchsia-500/10',
    order: 1,
  },
  'camera-exif': {
    title: 'Camera EXIF',
    blurb: 'How PixelGuard treats capture metadata. EXIF is trivially forged and routinely stripped, so it is weighed against the visual read rather than trusted.',
    expects: 'Expected: capture EXIF reported where present; any disagreement with the visual read is surfaced, not resolved.',
    tone: 'text-emerald-700 dark:text-emerald-300 border-emerald-600/30 dark:border-emerald-500/30 bg-emerald-500/10',
    order: 2,
  },
  composite: {
    title: 'Composite',
    blurb: 'Images assembled from more than one source. ELA renders the compression history for a human to read — on its own it never proves manipulation.',
    expects: 'Expected: an ELA heatmap for visual review. ELA alone is not evidence of tampering.',
    tone: 'text-amber-700 dark:text-amber-300 border-amber-600/30 dark:border-amber-500/30 bg-amber-500/10',
    order: 3,
  },
}

/** Optional copy per filename. Unlisted files fall back to their filename. */
export const DESCRIPTIONS = {
  'Gemini_Generated_Image_jm7mr5jm7mr5jm7m.jpg': {
    title: 'SynthID provenance',
    detail: 'Generated by Google Imagen and still carrying a SynthID marker in the file.',
  },
  'image.png': {
    title: 'Generated, metadata stripped',
    detail: 'No metadata survives, so nothing corroborates the visual read — the common case for anything re-saved or downloaded.',
  },
  'Pasted image.png': {
    title: 'Pasted from clipboard',
    detail: 'Clipboard paste discards the original container, and with it any provenance marker.',
  },
  'tiger.jpg': {
    title: 'Photograph, EXIF stripped',
    detail: 'A photograph whose capture metadata is gone, as it would be after almost any upload.',
  },
  'apple.jpg': {
    title: 'Product shot, no metadata',
    detail: 'Nothing left to corroborate or contradict the visual read.',
  },
  'images.jpg': {
    title: 'Downloaded photograph',
    detail: 'Saved from the web, so the capture metadata did not survive the round trip.',
  },
  'compose.jpg': {
    title: 'Composite A',
    detail: 'Assembled from multiple sources and re-saved, which is what erases most of the ELA trace.',
  },
  'compose2.jpg': {
    title: 'Composite B',
    detail: 'A second composite, for comparing how differently two edits register.',
  },
  '2-Figure2-1.png': {
    title: 'Side-by-side figure',
    detail: 'Panels from different sources in one frame — distinct compression histories in a single image.',
  },
}

/** "Gemini_Generated_Image_ab12.jpg" -> "Gemini Generated Image ab12" */
function titleFromFilename(file) {
  const base = file.replace(/\.[^.]+$/, '').replace(/[_-]+/g, ' ').replace(/\s+/g, ' ').trim()
  return base.charAt(0).toUpperCase() + base.slice(1)
}

/** Group every discovered file under its folder, newest config order first. */
export const SAMPLE_CATEGORIES = Object.entries(
  Object.entries(FILES).reduce((acc, [path, url]) => {
    const parts = path.split('/')
    const file = parts.pop()
    const category = parts.pop()
    ;(acc[category] ||= []).push({ file, url, ...(DESCRIPTIONS[file] || {}) })
    return acc
  }, {}),
).map(([id, samples]) => {
  const meta = CATEGORY_META[id] || {
    title: titleFromFilename(id),
    blurb: '',
    expects: '',
    tone: 'text-muted bg-raised border-line',
    order: 99,
  }
  return {
    id,
    ...meta,
    samples: samples
      .map((s) => ({ title: titleFromFilename(s.file), detail: '', ...s }))
      .sort((a, b) => a.file.localeCompare(b.file)),
  }
}).sort((a, b) => a.order - b.order)
